//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSIM.Cloud.Runner.APSOIL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.apsim.info/", ConfigurationName="APSOIL.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SoilNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/AllSoilNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] AllSoilNames(bool IncludeUserSoils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/UpdateAllSoils", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateAllSoils(string Contents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SoilXML(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/GetSoilInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilInfo GetSoilInfo(string SoilName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/GetSoilAnalysisInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilAnalysisInfo GetSoilAnalysisInfo(string SoilName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SoilTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/PAW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double PAW(string SoilName, double[] Thickness, double[] SW, bool IsGravimetric, string CropName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/PAWC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double PAWC(string SoilName, string CropName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/ConvertSoilSampleXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConvertSoilSampleXML(string SoilSampleXML);
        
        // CODEGEN: Parameter 'SoilChartPNGResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilChartPNG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilChartPNGResponse SoilChartPNG(APSIM.Cloud.Runner.APSOIL.SoilChartPNGRequest request);
        
        // CODEGEN: Parameter 'SoilChartWithSamplePNGResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilChartWithSamplePNG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGResponse SoilChartWithSamplePNG(APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SearchSoilsReturnInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilInfo[] SearchSoilsReturnInfo(double Latitude, double Longitude, double Radius, string SoilType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilAsJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SoilAsJson(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/UpdateUserSoil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateUserSoil(APSIM.Cloud.Runner.APSOIL.JsonSoilParam Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/PAWCJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.PAWCByCrop[] PAWCJson(APSIM.Cloud.Runner.APSOIL.PAWCJsonParams Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SearchSoils", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilInfo[] SearchSoils(APSIM.Cloud.Runner.APSOIL.SearchSoilsParams Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/AllAustralianSoils", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilBasicInfo[] AllAustralianSoils(APSIM.Cloud.Runner.APSOIL.SearchSoilsParams Params);
        
        // CODEGEN: Parameter 'SoilChartPNGFromXMLResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.apsim.info/SoilChartPNGFromXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLResponse SoilChartPNGFromXML(APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class SoilInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string descriptionField;
        
        private string soilTypeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private double distanceField;
        
        private string aSCOrderField;
        
        private string aSCSubOrderField;
        
        private string siteField;
        
        private string regionField;
        
        private string nearestTownField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SoilType {
            get {
                return this.soilTypeField;
            }
            set {
                this.soilTypeField = value;
                this.RaisePropertyChanged("SoilType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ASCOrder {
            get {
                return this.aSCOrderField;
            }
            set {
                this.aSCOrderField = value;
                this.RaisePropertyChanged("ASCOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ASCSubOrder {
            get {
                return this.aSCSubOrderField;
            }
            set {
                this.aSCSubOrderField = value;
                this.RaisePropertyChanged("ASCSubOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("Site");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string NearestTown {
            get {
                return this.nearestTownField;
            }
            set {
                this.nearestTownField = value;
                this.RaisePropertyChanged("NearestTown");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class SoilBasicInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class SearchSoilsParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double latitudeField;
        
        private double longitudeField;
        
        private double radiusField;
        
        private string aSCOrderField;
        
        private string aSCSubOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
                this.RaisePropertyChanged("Radius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ASCOrder {
            get {
                return this.aSCOrderField;
            }
            set {
                this.aSCOrderField = value;
                this.RaisePropertyChanged("ASCOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ASCSubOrder {
            get {
                return this.aSCSubOrderField;
            }
            set {
                this.aSCSubOrderField = value;
                this.RaisePropertyChanged("ASCSubOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class PAWCByCrop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cropNameField;
        
        private double[] pAWCField;
        
        private double pAWCTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CropName {
            get {
                return this.cropNameField;
            }
            set {
                this.cropNameField = value;
                this.RaisePropertyChanged("CropName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public double[] PAWC {
            get {
                return this.pAWCField;
            }
            set {
                this.pAWCField = value;
                this.RaisePropertyChanged("PAWC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double PAWCTotal {
            get {
                return this.pAWCTotalField;
            }
            set {
                this.pAWCTotalField = value;
                this.RaisePropertyChanged("PAWCTotal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class PAWCJsonParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jSonSoilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string JSonSoil {
            get {
                return this.jSonSoilField;
            }
            set {
                this.jSonSoilField = value;
                this.RaisePropertyChanged("JSonSoil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class JsonSoilParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jSonSoilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string JSonSoil {
            get {
                return this.jSonSoilField;
            }
            set {
                this.jSonSoilField = value;
                this.RaisePropertyChanged("JSonSoil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apsim.info/")]
    public partial class SoilAnalysisInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private double[] thicknessField;
        
        private string[] textureField;
        
        private double[] ecField;
        
        private double[] phField;
        
        private double[] clField;
        
        private double[] boronField;
        
        private double[] eSPField;
        
        private double[] alField;
        
        private double[] wheatLLField;
        
        private double[] wheatXFField;
        
        private double[] lL15Field;
        
        private double[] dULField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public double[] Thickness {
            get {
                return this.thicknessField;
            }
            set {
                this.thicknessField = value;
                this.RaisePropertyChanged("Thickness");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] Texture {
            get {
                return this.textureField;
            }
            set {
                this.textureField = value;
                this.RaisePropertyChanged("Texture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public double[] EC {
            get {
                return this.ecField;
            }
            set {
                this.ecField = value;
                this.RaisePropertyChanged("EC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public double[] PH {
            get {
                return this.phField;
            }
            set {
                this.phField = value;
                this.RaisePropertyChanged("PH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public double[] CL {
            get {
                return this.clField;
            }
            set {
                this.clField = value;
                this.RaisePropertyChanged("CL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public double[] Boron {
            get {
                return this.boronField;
            }
            set {
                this.boronField = value;
                this.RaisePropertyChanged("Boron");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public double[] ESP {
            get {
                return this.eSPField;
            }
            set {
                this.eSPField = value;
                this.RaisePropertyChanged("ESP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public double[] AL {
            get {
                return this.alField;
            }
            set {
                this.alField = value;
                this.RaisePropertyChanged("AL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public double[] WheatLL {
            get {
                return this.wheatLLField;
            }
            set {
                this.wheatLLField = value;
                this.RaisePropertyChanged("WheatLL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public double[] WheatXF {
            get {
                return this.wheatXFField;
            }
            set {
                this.wheatXFField = value;
                this.RaisePropertyChanged("WheatXF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public double[] LL15 {
            get {
                return this.lL15Field;
            }
            set {
                this.lL15Field = value;
                this.RaisePropertyChanged("LL15");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public double[] DUL {
            get {
                return this.dULField;
            }
            set {
                this.dULField = value;
                this.RaisePropertyChanged("DUL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoilChartPNG", WrapperNamespace="http://www.apsim.info/", IsWrapped=true)]
    public partial class SoilChartPNGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=0)]
        public string SoilName;
        
        public SoilChartPNGRequest() {
        }
        
        public SoilChartPNGRequest(string SoilName) {
            this.SoilName = SoilName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoilChartPNGResponse", WrapperNamespace="http://www.apsim.info/", IsWrapped=true)]
    public partial class SoilChartPNGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SoilChartPNGResult;
        
        public SoilChartPNGResponse() {
        }
        
        public SoilChartPNGResponse(byte[] SoilChartPNGResult) {
            this.SoilChartPNGResult = SoilChartPNGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoilChartWithSamplePNG", WrapperNamespace="http://www.apsim.info/", IsWrapped=true)]
    public partial class SoilChartWithSamplePNGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=0)]
        public string SoilName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=1)]
        public double[] Thickness;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=2)]
        public double[] SW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=3)]
        public bool IsGravimetric;
        
        public SoilChartWithSamplePNGRequest() {
        }
        
        public SoilChartWithSamplePNGRequest(string SoilName, double[] Thickness, double[] SW, bool IsGravimetric) {
            this.SoilName = SoilName;
            this.Thickness = Thickness;
            this.SW = SW;
            this.IsGravimetric = IsGravimetric;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoilChartWithSamplePNGResponse", WrapperNamespace="http://www.apsim.info/", IsWrapped=true)]
    public partial class SoilChartWithSamplePNGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SoilChartWithSamplePNGResult;
        
        public SoilChartWithSamplePNGResponse() {
        }
        
        public SoilChartWithSamplePNGResponse(byte[] SoilChartWithSamplePNGResult) {
            this.SoilChartWithSamplePNGResult = SoilChartWithSamplePNGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoilChartPNGFromXML", WrapperNamespace="http://www.apsim.info/", IsWrapped=true)]
    public partial class SoilChartPNGFromXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=0)]
        public string XML;
        
        public SoilChartPNGFromXMLRequest() {
        }
        
        public SoilChartPNGFromXMLRequest(string XML) {
            this.XML = XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoilChartPNGFromXMLResponse", WrapperNamespace="http://www.apsim.info/", IsWrapped=true)]
    public partial class SoilChartPNGFromXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.apsim.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SoilChartPNGFromXMLResult;
        
        public SoilChartPNGFromXMLResponse() {
        }
        
        public SoilChartPNGFromXMLResponse(byte[] SoilChartPNGFromXMLResult) {
            this.SoilChartPNGFromXMLResult = SoilChartPNGFromXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : APSIM.Cloud.Runner.APSOIL.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<APSIM.Cloud.Runner.APSOIL.ServiceSoap>, APSIM.Cloud.Runner.APSOIL.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] SoilNames() {
            return base.Channel.SoilNames();
        }
        
        public string[] AllSoilNames(bool IncludeUserSoils) {
            return base.Channel.AllSoilNames(IncludeUserSoils);
        }
        
        public void UpdateAllSoils(string Contents) {
            base.Channel.UpdateAllSoils(Contents);
        }
        
        public string SoilXML(string Name) {
            return base.Channel.SoilXML(Name);
        }
        
        public APSIM.Cloud.Runner.APSOIL.SoilInfo GetSoilInfo(string SoilName) {
            return base.Channel.GetSoilInfo(SoilName);
        }
        
        public APSIM.Cloud.Runner.APSOIL.SoilAnalysisInfo GetSoilAnalysisInfo(string SoilName) {
            return base.Channel.GetSoilAnalysisInfo(SoilName);
        }
        
        public string[] SoilTypes() {
            return base.Channel.SoilTypes();
        }
        
        public double PAW(string SoilName, double[] Thickness, double[] SW, bool IsGravimetric, string CropName) {
            return base.Channel.PAW(SoilName, Thickness, SW, IsGravimetric, CropName);
        }
        
        public double PAWC(string SoilName, string CropName) {
            return base.Channel.PAWC(SoilName, CropName);
        }
        
        public string ConvertSoilSampleXML(string SoilSampleXML) {
            return base.Channel.ConvertSoilSampleXML(SoilSampleXML);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APSIM.Cloud.Runner.APSOIL.SoilChartPNGResponse APSIM.Cloud.Runner.APSOIL.ServiceSoap.SoilChartPNG(APSIM.Cloud.Runner.APSOIL.SoilChartPNGRequest request) {
            return base.Channel.SoilChartPNG(request);
        }
        
        public byte[] SoilChartPNG(string SoilName) {
            APSIM.Cloud.Runner.APSOIL.SoilChartPNGRequest inValue = new APSIM.Cloud.Runner.APSOIL.SoilChartPNGRequest();
            inValue.SoilName = SoilName;
            APSIM.Cloud.Runner.APSOIL.SoilChartPNGResponse retVal = ((APSIM.Cloud.Runner.APSOIL.ServiceSoap)(this)).SoilChartPNG(inValue);
            return retVal.SoilChartPNGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGResponse APSIM.Cloud.Runner.APSOIL.ServiceSoap.SoilChartWithSamplePNG(APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGRequest request) {
            return base.Channel.SoilChartWithSamplePNG(request);
        }
        
        public byte[] SoilChartWithSamplePNG(string SoilName, double[] Thickness, double[] SW, bool IsGravimetric) {
            APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGRequest inValue = new APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGRequest();
            inValue.SoilName = SoilName;
            inValue.Thickness = Thickness;
            inValue.SW = SW;
            inValue.IsGravimetric = IsGravimetric;
            APSIM.Cloud.Runner.APSOIL.SoilChartWithSamplePNGResponse retVal = ((APSIM.Cloud.Runner.APSOIL.ServiceSoap)(this)).SoilChartWithSamplePNG(inValue);
            return retVal.SoilChartWithSamplePNGResult;
        }
        
        public APSIM.Cloud.Runner.APSOIL.SoilInfo[] SearchSoilsReturnInfo(double Latitude, double Longitude, double Radius, string SoilType) {
            return base.Channel.SearchSoilsReturnInfo(Latitude, Longitude, Radius, SoilType);
        }
        
        public string SoilAsJson(string Name) {
            return base.Channel.SoilAsJson(Name);
        }
        
        public bool UpdateUserSoil(APSIM.Cloud.Runner.APSOIL.JsonSoilParam Params) {
            return base.Channel.UpdateUserSoil(Params);
        }
        
        public APSIM.Cloud.Runner.APSOIL.PAWCByCrop[] PAWCJson(APSIM.Cloud.Runner.APSOIL.PAWCJsonParams Params) {
            return base.Channel.PAWCJson(Params);
        }
        
        public APSIM.Cloud.Runner.APSOIL.SoilInfo[] SearchSoils(APSIM.Cloud.Runner.APSOIL.SearchSoilsParams Params) {
            return base.Channel.SearchSoils(Params);
        }
        
        public APSIM.Cloud.Runner.APSOIL.SoilBasicInfo[] AllAustralianSoils(APSIM.Cloud.Runner.APSOIL.SearchSoilsParams Params) {
            return base.Channel.AllAustralianSoils(Params);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLResponse APSIM.Cloud.Runner.APSOIL.ServiceSoap.SoilChartPNGFromXML(APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLRequest request) {
            return base.Channel.SoilChartPNGFromXML(request);
        }
        
        public byte[] SoilChartPNGFromXML(string XML) {
            APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLRequest inValue = new APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLRequest();
            inValue.XML = XML;
            APSIM.Cloud.Runner.APSOIL.SoilChartPNGFromXMLResponse retVal = ((APSIM.Cloud.Runner.APSOIL.ServiceSoap)(this)).SoilChartPNGFromXML(inValue);
            return retVal.SoilChartPNGFromXMLResult;
        }
    }
}
