//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSIM.Cloud.Runner.F4P {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="F4P.IF4P")]
    public interface IF4P {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IF4P/StoreReport", ReplyAction="http://tempuri.org/IF4P/StoreReportResponse")]
        void StoreReport(string aReportName, System.Data.DataSet aReportData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IF4P/StoreBusinessPlannerResults", ReplyAction="http://tempuri.org/IF4P/StoreBusinessPlannerResultsResponse")]
        void StoreBusinessPlannerResults(string aUserName, string aResultsXML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IF4PChannel : APSIM.Cloud.Runner.F4P.IF4P, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class F4PClient : System.ServiceModel.ClientBase<APSIM.Cloud.Runner.F4P.IF4P>, APSIM.Cloud.Runner.F4P.IF4P {
        
        public F4PClient() {
        }
        
        public F4PClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public F4PClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public F4PClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public F4PClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StoreReport(string aReportName, System.Data.DataSet aReportData) {
            base.Channel.StoreReport(aReportName, aReportData);
        }
        
        public void StoreBusinessPlannerResults(string aUserName, string aResultsXML) {
            base.Channel.StoreBusinessPlannerResults(aUserName, aResultsXML);
        }
    }
}
