//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace CallReportingWebService.YP.com.au {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IReporting", Namespace="http://tempuri.org/")]
    public partial class Reporting : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StoreReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Reporting() {
            this.Url = global::CallReportingWebService.Properties.Settings.Default.CallReportingWebService_YP_com_au_Reporting;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StoreReportCompletedEventHandler StoreReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReporting/StoreReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StoreReport([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.DataTable aReportData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string aReportName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string aUserName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string aPaddockName, ReportType aReportType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aReportTypeSpecified, out bool StoreReportResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool StoreReportResultSpecified) {
            object[] results = this.Invoke("StoreReport", new object[] {
                        aReportData,
                        aReportName,
                        aUserName,
                        aPaddockName,
                        aReportType,
                        aReportTypeSpecified});
            StoreReportResult = ((bool)(results[0]));
            StoreReportResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void StoreReportAsync(System.Data.DataTable aReportData, string aReportName, string aUserName, string aPaddockName, ReportType aReportType, bool aReportTypeSpecified) {
            this.StoreReportAsync(aReportData, aReportName, aUserName, aPaddockName, aReportType, aReportTypeSpecified, null);
        }
        
        /// <remarks/>
        public void StoreReportAsync(System.Data.DataTable aReportData, string aReportName, string aUserName, string aPaddockName, ReportType aReportType, bool aReportTypeSpecified, object userState) {
            if ((this.StoreReportOperationCompleted == null)) {
                this.StoreReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoreReportOperationCompleted);
            }
            this.InvokeAsync("StoreReport", new object[] {
                        aReportData,
                        aReportName,
                        aUserName,
                        aPaddockName,
                        aReportType,
                        aReportTypeSpecified}, this.StoreReportOperationCompleted, userState);
        }
        
        private void OnStoreReportOperationCompleted(object arg) {
            if ((this.StoreReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoreReportCompleted(this, new StoreReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/YPService")]
    public enum ReportType {
        
        /// <remarks/>
        ClimateAdaptationReport,
        
        /// <remarks/>
        ClimateChangeReport,
        
        /// <remarks/>
        BasicCropReport,
        
        /// <remarks/>
        CropReport,
        
        /// <remarks/>
        SoilProbeCropReport,
        
        /// <remarks/>
        FallowMonitoringReport,
        
        /// <remarks/>
        IrrigationComparisonReport,
        
        /// <remarks/>
        IrrigationProfitReportBarley,
        
        /// <remarks/>
        IrrigationProfitReportWheat,
        
        /// <remarks/>
        NitrogenComparisonReport,
        
        /// <remarks/>
        NitogenProfitReportBarley,
        
        /// <remarks/>
        NitogenProfitReportWheat,
        
        /// <remarks/>
        SowingXVarietyReport,
        
        /// <remarks/>
        SowingOpportunityReport,
        
        /// <remarks/>
        StubbleManagementReport,
        
        /// <remarks/>
        HayProfitReport,
        
        /// <remarks/>
        CurrentGrowthStageReport,
        
        /// <remarks/>
        WeatherStationValidationReport,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void StoreReportCompletedEventHandler(object sender, StoreReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StoreReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StoreReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool StoreReportResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool StoreReportResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591